name: Fetch devcontainer

on:
  schedule:
    - cron: "21 8 * * *" # run every day at 1:20 AM PST
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: chrispyles/devcontainer-action@main
      with:
        repo: chrispyles/ds-devcontainer
