name: Fetch devcontainer

on:
  schedule:
    - cron: "21 8 * * *" # run every day at 1:20 AM PST
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      DEVCONTAINER_REPO: "chrispyles/ds-devcontainer"

    steps:
    - uses: actions/checkout@v2

    - name: Set git configurations
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Clone devcontainer repo
      id: clone
      run: |
        rm -rf .devcontainer
        git clone https://github.com/$DEVCONTAINER_REPO .devcontainer
        echo "::set-output name=sha::$(cd .devcontainer && git rev-parse HEAD)"
        rm -rf .devcontainer/.git*

    - name: Commit submodule updates
      run: |
        git add .devcontainer
        git commit -m "update devcontainer to $DEVCONTAINER_REPO@${{ steps.clone.outputs.sha }}" || :
        git push
